"""order scheduled_at

Revision ID: 4531134421ff
Revises: 4ab90e5cf41d
Create Date: 2026-06-11 13:50:56.926048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4531134421ff'
down_revision: Union[str, Sequence[str], None] = '4ab90e5cf41d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'scheduled_at')
    # ### end Alembic commands ###
