"""review unique author per order

Revision ID: 4ab90e5cf41d
Revises: b12a5355d41a
Create Date: 2026-06-11 10:04:40.140300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4ab90e5cf41d'
down_revision: Union[str, Sequence[str], None] = 'b12a5355d41a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_review_order_author', 'review', ['order_id', 'from_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_review_order_author', 'review', type_='unique')
    # ### end Alembic commands ###
